In [1]:
from __future__ import absolute_import, division, print_function

import numpy as np
import tensorflow as tf
import tensorflow.contrib.eager as tfe

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
# Set Eager API# Set E 
print("Setting Eager mode...")
tfe.enable_eager_execution()

Setting Eager mode...


In [7]:
print("Define constant tensors")
a = tf.constant(2)
print("a = %i" % a)
b = tf.constant(3)
print("b = %i" % b)

Define constant tensors
a = 2
b = 3


In [8]:
print("Running operations, with tf.Session")
c = a + b
print("a + b = %i" % c)

d = a * b
print("a * b = %i" % d)

Running operations, with tf.Session
a + b = 5
a * b = 6


In [16]:
# 与numpy交互
a = tf.constant([[2., 1.], [1., 0.]], dtype=tf.float32)
b = tf.constant([[3., 0.], [5., 1.]], dtype=np.float32)
print("Tensor: \na = %s" % a)
print("Numpy: \nb = %s" % b)

Tensor: 
a = tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
Numpy: 
b = tf.Tensor(
[[3. 0.]
 [5. 1.]], shape=(2, 2), dtype=float32)


In [18]:
print("Running oeprations, without tf.Session")
c = a + b
print("a + b = %s" %c) 

Running oeprations, without tf.Session
a + b = tf.Tensor(
[[5. 1.]
 [6. 1.]], shape=(2, 2), dtype=float32)


In [19]:
d = tf.matmul(a, b)
print("a * b = %s" % d)

a * b = tf.Tensor(
[[11.  1.]
 [ 3.  0.]], shape=(2, 2), dtype=float32)


In [20]:
print("iterate through Tensor 'a':")
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][i])

iterate through Tensor 'a':
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
